/* This file is autogenerated from Version.h.in */

#define RUBYCOCOA_VERSION_BARE 0.13.2
#define RUBYCOCOA_VERSION_SHORT 0.13.2
#define RUBYCOCOA_VERSION       "0.13.2"
#define RUBYCOCOA_RELEASE_DATE  "2008-02-13"
#define RUBYCOCOA_SVN_REVISION  "2230"
